//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityDroid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int Activities = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int AddActivity = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int Email = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Go = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Status = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int Username = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int textView2 = 2131034112;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000b
			public const int Activities = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int AddActivity = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int ApiPath = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int DeviceName = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int DeviceType = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Email = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int Find = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int Go = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Status = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int Stop = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int Username = 2130968577;
			
			private String()
			{
			}
		}
	}
}
